# Generated by Django 5.1.6 on 2025-03-03 05:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Script",
            fields=[
                ("scriptId", models.AutoField(primary_key=True, serialize=False)),
                ("scriptTitle", models.CharField(max_length=255)),
                ("character_links", models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                ("comment_id", models.AutoField(primary_key=True, serialize=False)),
                ("user_name", models.CharField(default="未知", max_length=255)),
                ("comment_text", models.TextField()),
                ("comment_time", models.DateTimeField()),
                (
                    "sentiment",
                    models.CharField(
                        choices=[("褒义", "褒义"), ("中性", "中性"), ("贬义", "贬义")],
                        default="中性",
                        max_length=10,
                    ),
                ),
                (
                    "script",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="scripts.script"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Character",
            fields=[
                ("character_id", models.AutoField(primary_key=True, serialize=False)),
                ("character_name", models.CharField(max_length=255)),
                ("image_url", models.CharField(blank=True, max_length=255, null=True)),
                ("symbol_size", models.IntegerField(default=2)),
                ("value", models.IntegerField(default=0)),
                ("category", models.IntegerField(default=0)),
                (
                    "script",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="scripts.script"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WordCloud",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("words", models.JSONField()),
                (
                    "scriptId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wordclouds",
                        to="scripts.script",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Scene",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("scene_id", models.IntegerField()),
                ("scene_text", models.TextField()),
                (
                    "scriptId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="scripts.script"
                    ),
                ),
            ],
            options={
                "unique_together": {("scriptId", "scene_id")},
            },
        ),
    ]
