# Generated by Django 5.1.6 on 2025-03-03 05:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scripts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="sentiment",
            field=models.IntegerField(
                choices=[(-1, "贬义"), (0, "中性"), (1, "褒义")], default=0
            ),
        ),
    ]
